services:
  sernapesca-pipeline:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: kedro_polars_container
    volumes:
      - .:/app
    command: kedro run